site_name: Team Contagion's Knowledge Base
site_url: https://teamcontagion.github.io/knowledge-base

repo_name: TeamContagion/knowledge-base
repo_url: https://github.com/TeamContagion/knowledge-base
edit_uri: blob/master/docs

nav:
  - Home: index.md
  - About: about.md
  - Cryptography:
    - Introduction to Cryptography: crypto/introduction.md
    - Starting Point: crypto/starting-point.md
  - Forensics:
    - Introduction to Forensics: forensics/introduction.md
  - Pwn:
    - Introduction to Pwn: pwn/introduction.md
    - Tools: pwn/tools.md
    - ROP:
      - ROP 0 - Intro to ROP: pwn/rop/introduction.md
      - ROP 1 - Calling Functions: pwn/rop/functions.md
      - ROP 2 - Passing Parameters: pwn/rop/parameters.md
      - ROP 3 - ret2libc: pwn/rop/ret2libc.md
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: orange
    accent: cyan
  icon: 
    logo: material/biohazard
  features:
    - navigation.tabs
